# Generated by Django 5.0.6 on 2026-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HundredCheckpoint',
            fields=[
                ('checkpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkpoint_number', models.IntegerField()),
                ('start_global_index', models.IntegerField()),
                ('end_global_index', models.IntegerField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['checkpoint_number'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.IntegerField(db_index=True)),
                ('global_index', models.IntegerField(db_index=True)),
                ('speaker', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['global_index'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='idle', max_length=20)),
                ('current_step', models.CharField(default='', max_length=200)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('total_checkpoints', models.IntegerField(default=0)),
                ('error_message', models.TextField(default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processing Status',
            },
        ),
        migrations.CreateModel(
            name='TopicCheckpoint',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_number', models.IntegerField()),
                ('start_global_index', models.IntegerField()),
                ('end_global_index', models.IntegerField()),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic_number'],
            },
        ),
    ]
