# Generated by Django 5.2.10 on 2026-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccheckpoint',
            name='conversation_day_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topiccheckpoint',
            name='conversation_day_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
